export type Gen2MonitorKind = "host" | "docker" | "ollama" | "terminal" | "reports" | "facility" | "staff" | "cultivation" | "production";

export type Gen2RoomOperation = {
  roomId: string;
  title: string;
  owner: string;
  monitorKind: Gen2MonitorKind;
  primaryAction: string;
  watches: string[];
  reportTo: string;
  alertRules: string[];
};

export type Gen2WorkerProfile = {
  npcId: string;
  stationRoomId: string;
  department: string;
  title: string;
  personality: string;
  currentAction: string;
  steadyMood: string;
  busyMood: string;
  reportTarget: string;
  breakPolicy: string;
};

export type Gen2HotKey = {
  key: string;
  label: string;
  message: string;
  expectedResponse: string;
};

export type Gen2WorkerIdentity = {
  name: string;
  sex: string;
  age: number;
  workEthic: "LOW" | "STEADY" | "HIGH" | "EXCELLENT";
  evaluation: string;
};

export type Gen2RoomVital = {
  status: "OK" | "BUSY" | "WATCH" | "ALERT";
  primary: string;
  secondary: string;
  detail: string[];
};

export const gen2RoomOperations: Record<string, Gen2RoomOperation> = {
  boss: {
    roomId: "boss",
    title: "Boss Debrief Office",
    owner: "Boss",
    monitorKind: "reports",
    primaryAction: "Compile manager summaries, security warnings, and owner instructions into a daily debrief.",
    watches: ["Manager reports", "Security escalations", "WO report log", "Owner hot-key messages"],
    reportTo: "Owner",
    alertRules: ["Escalate overloads", "Flag repeated breaks", "Praise strong recovery after high load"],
  },
  clone: {
    roomId: "clone",
    title: "Clone Health Watch",
    owner: "Cultivation worker",
    monitorKind: "cultivation",
    primaryAction: "Display HP Laptop telemetry as clone health, water pressure, and light availability.",
    watches: ["HP Laptop online state", "CPU load", "Memory pressure", "Worker checks"],
    reportTo: "Cultivation Manager",
    alertRules: ["Dry trays", "Lights offline", "No worker check within schedule"],
  },
  mother: {
    roomId: "mother",
    title: "Mother Plant Watch",
    owner: "Cultivation worker",
    monitorKind: "cultivation",
    primaryAction: "Display NukeBox host telemetry as the mother system controlling the facility.",
    watches: ["NukeBox CPU", "NukeBox RAM", "Irrigation load", "Canopy status"],
    reportTo: "Cultivation Manager",
    alertRules: ["CO2 low", "Canopy stress", "Irrigation missed"],
  },
  grow1: {
    roomId: "grow1",
    title: "Grow Room 1 Cycle",
    owner: "Cultivation worker",
    monitorKind: "cultivation",
    primaryAction: "Monitor BAK3RY telemetry through grow lights, irrigation, and plant condition.",
    watches: ["BAK3RY online state", "CPU", "RAM", "Worker activity"],
    reportTo: "Cultivation Manager",
    alertRules: ["Temperature high", "Water low", "Too many missed checks"],
  },
  grow2: {
    roomId: "grow2",
    title: "Grow Room 2 Cycle",
    owner: "Cultivation worker",
    monitorKind: "cultivation",
    primaryAction: "Monitor Hack-Safe Raspberry Pi 5 telemetry and compare it against BAK3RY.",
    watches: ["Hack-Safe online state", "CPU", "RAM", "Worker activity"],
    reportTo: "Cultivation Manager",
    alertRules: ["Temperature high", "Water low", "Trend mismatch vs Grow Room 1"],
  },
  grow3: {
    roomId: "grow3",
    title: "Grow Room 3 Device Watch",
    owner: "Cultivation worker",
    monitorKind: "cultivation",
    primaryAction: "Hold the third grow bay ready for the future PI3 telemetry feed.",
    watches: ["PI3 assignment", "Telemetry arrival", "Light readiness", "Worker preparation"],
    reportTo: "Cultivation Manager",
    alertRules: ["Long heavy load", "Temperature high", "Network stall"],
  },
  grow4: {
    roomId: "grow4",
    title: "Grow Room 4 Device Watch",
    owner: "Cultivation worker",
    monitorKind: "cultivation",
    primaryAction: "Display The Garden Oracle VM telemetry as plant stress, irrigation demand, and light state.",
    watches: ["The Garden online state", "CPU load", "RAM pressure", "Swap pressure", "Network speed"],
    reportTo: "Cultivation Manager",
    alertRules: ["Long heavy load", "Swap high", "Storage slow"],
  },
  soil: {
    roomId: "soil",
    title: "Harvest Dry Room",
    owner: "Cultivation worker",
    monitorKind: "cultivation",
    primaryAction: "Receive cut plants from grow rooms, monitor drying racks, and release cured material to trim.",
    watches: ["Drying racks", "Humidity", "Harvest batches", "Trim handoff"],
    reportTo: "Cultivation Manager",
    alertRules: ["Humidity high", "Dry batch delayed", "Trim handoff overdue"],
  },
  potting: {
    roomId: "potting",
    title: "Potting Queue",
    owner: "Cultivation worker",
    monitorKind: "production",
    primaryAction: "Blend soil and nutrients, fill open pots, and stage repotted clones for grow rooms.",
    watches: ["Potting mix", "Nutrient barrels", "Open pots", "Clone transplants"],
    reportTo: "Cultivation Manager",
    alertRules: ["Queue backing up", "Worker overextended", "Missing potting report"],
  },
  cultMgr: {
    roomId: "cultMgr",
    title: "Cultivation Manager Desk",
    owner: "Cultivation Manager",
    monitorKind: "staff",
    primaryAction: "Collect cultivation worker lists, balance breaks, assist overloaded staff, and summarize to boss.",
    watches: ["Worker break rate", "Plant-room alerts", "Task completion list", "Department morale"],
    reportTo: "Boss",
    alertRules: ["Too many breaks", "Worker overworked", "Critical plant-room alert"],
  },
  trim: {
    roomId: "trim",
    title: "Processing Trim Queue",
    owner: "Processing worker",
    monitorKind: "production",
    primaryAction: "Receive dry harvest, operate trim tables, and release prepared batches to packaging.",
    watches: ["Dry harvest queue", "Table activity", "Package handoff", "Yield notes"],
    reportTo: "Operations Manager",
    alertRules: ["Queue stuck", "Machine offline", "Worker fatigue"],
  },
  pack: {
    roomId: "pack",
    title: "Packaging Station",
    owner: "Processing worker",
    monitorKind: "production",
    primaryAction: "Package trimmed harvest, label batches, and send finished packages to loading.",
    watches: ["Crates", "Conveyor", "Label queue", "Batch WO"],
    reportTo: "Operations Manager",
    alertRules: ["Labels low", "Conveyor stopped", "Batch mismatch"],
  },
  extract: {
    roomId: "extract",
    title: "Extraction Equipment",
    owner: "Operations Manager",
    monitorKind: "facility",
    primaryAction: "Monitor extractor, vats, pipes, pressure/temperature, and safety status.",
    watches: ["Extractor temp", "Tank pressure", "Pipe status", "Safety lock"],
    reportTo: "Security and Boss",
    alertRules: ["Temperature high", "Pressure high", "Safety lock open"],
  },
  security: {
    roomId: "security",
    title: "Security Watch",
    owner: "Security",
    monitorKind: "facility",
    primaryAction: "Watch all rooms for overloads, heat, offline systems, and suspicious inactivity.",
    watches: ["Room alerts", "Temperature warnings", "Worker status", "Camera wall"],
    reportTo: "Boss",
    alertRules: ["Any critical alert", "Room too hot", "Worker missing from station"],
  },
  ops: {
    roomId: "ops",
    title: "Docker Operations",
    owner: "Operations Manager",
    monitorKind: "docker",
    primaryAction: "Monitor Docker daemon, containers, uptime, restart count, CPU, memory, and network throughput.",
    watches: ["Container uptime", "CPU and memory", "Restart count", "Image age", "Port health"],
    reportTo: "Boss",
    alertRules: ["Container down", "Restart loop", "Memory pressure", "Port offline"],
  },
  break: {
    roomId: "break",
    title: "Break Rotation",
    owner: "Managers",
    monitorKind: "staff",
    primaryAction: "Let workers rest when workload is steady while managers watch for too many breaks.",
    watches: ["Break count", "Mood recovery", "Department coverage", "Return-to-station timer"],
    reportTo: "Department Managers",
    alertRules: ["Too many breaks", "Department uncovered", "Worker needs relief"],
  },
  bath: {
    roomId: "bath",
    title: "Bathroom Occupancy",
    owner: "Managers",
    monitorKind: "staff",
    primaryAction: "Allow one worker at a time and queue anyone else back to break room or department.",
    watches: ["Occupancy", "Queue", "Return timer"],
    reportTo: "Department Managers",
    alertRules: ["More than one occupant", "Stay too long"],
  },
  screen: {
    roomId: "screen",
    title: "Grow Ops Screening",
    owner: "Grow Ops",
    monitorKind: "staff",
    primaryAction: "Screen new facility staff, set sprite colors, and send saved hires onto the floor.",
    watches: ["New staff profiles", "Department colors", "Role assignments", "Entry queue"],
    reportTo: "Boss",
    alertRules: ["Missing title", "Unassigned department", "Unsaved profile edit"],
  },
  dock: {
    roomId: "dock",
    title: "Logistics Staging",
    owner: "Logistics",
    monitorKind: "reports",
    primaryAction: "Stage finished packages alongside report packets before warehouse intake.",
    watches: ["Finished packages", "WO numbers", "Report packets", "Delivery status"],
    reportTo: "Boss",
    alertRules: ["Report missing WO", "Delivery overdue"],
  },
  warehouse: {
    roomId: "warehouse",
    title: "Report and Supply Archive",
    owner: "Logistics",
    monitorKind: "reports",
    primaryAction: "Store finished packages and deliver timestamped staff reports to the Markdown WO archive.",
    watches: ["Package inventory", "WO log", "Report archive", "Markdown sync"],
    reportTo: "Boss",
    alertRules: ["Write failure", "WO duplicate", "Archive delayed"],
  },
  sales: {
    roomId: "sales",
    title: "GMKtec M7 Host Monitor",
    owner: "Boss Executive",
    monitorKind: "host",
    primaryAction: "Monitor Windows host health for CPU, RAM, clocks, fans, thermals, disks, network, and uptime.",
    watches: ["CPU speed/load", "RAM usage/capacity", "Fan RPM", "Temperatures", "Disk and network"],
    reportTo: "Boss",
    alertRules: ["CPU hot", "RAM pressure", "Fan abnormal", "Disk low"],
  },
  rd1: {
    roomId: "rd1",
    title: "Ollama Model Lab",
    owner: "Researcher",
    monitorKind: "ollama",
    primaryAction: "Monitor Ollama service, loaded models, model size, VRAM/RAM use, latency, and queue status.",
    watches: ["Ollama uptime", "Loaded models", "Model latency", "Token throughput", "Queue length"],
    reportTo: "Boss",
    alertRules: ["Ollama offline", "Model too slow", "Memory pressure", "Queue stuck"],
  },
  rd2: {
    roomId: "rd2",
    title: "Terminal and SSH Workbench",
    owner: "Researcher",
    monitorKind: "terminal",
    primaryAction: "Run approved commands, open terminals, and connect to PCs, Raspberry Pis, and VMs over SSH.",
    watches: ["Approval queue", "Command history", "SSH targets", "Terminal sessions"],
    reportTo: "Boss",
    alertRules: ["Approval needed", "Command failed", "SSH offline", "Session stale"],
  },
};

export const gen2RoomVitals: Record<string, Gen2RoomVital> = {
  boss: { status: "OK", primary: "BRIEF 3", secondary: "WO READY", detail: ["MANAGER REPORTS: 3", "SECURITY FLAGS: 0", "OWNER NOTES: READY"] },
  clone: { status: "OK", primary: "RH 62%", secondary: "TRAYS 8", detail: ["LIGHT: ON", "WATER: NORMAL", "CHECKS: ON SCHEDULE"] },
  mother: { status: "OK", primary: "PC 64C", secondary: "FAN OK", detail: ["CPU: 22%", "RAM: 11/32G", "SWAP: 1.2G", "NET: 42MB"] },
  grow1: { status: "BUSY", primary: "PI1 67C", secondary: "AIR 71%", detail: ["CPU->WATER: 48%", "RAM->GROWTH: 62%", "NET->HARVEST: 6D"] },
  grow2: { status: "OK", primary: "PI2 61C", secondary: "AIR 76%", detail: ["CPU->WATER: 31%", "RAM->HEIGHT: 58%", "DISK->ROOTS: GOOD"] },
  grow3: { status: "WATCH", primary: "PI3 78C", secondary: "AIR 45%", detail: ["CPU->WATER: 86%", "SWAP->STRESS: HIGH", "PLANTS: YELLOWING"] },
  grow4: { status: "OK", primary: "VM4 55C", secondary: "AIR 81%", detail: ["CPU->WATER: 28%", "RAM->GROWTH: 69%", "NET->HARVEST: 9D"] },
  soil: { status: "BUSY", primary: "DRYING 4", secondary: "RH 54%", detail: ["RACKS: ACTIVE", "NEXT TRIM: 2 BATCH", "AIRFLOW: GOOD"] },
  potting: { status: "BUSY", primary: "POTS 5", secondary: "MIX READY", detail: ["CLONES READY: 3", "BARRELS: FULL", "WO: OPEN"] },
  cultMgr: { status: "OK", primary: "STAFF 3", secondary: "BREAKS 1", detail: ["REPORTS: 3", "ASSIST: NONE", "MORALE: STABLE"] },
  trim: { status: "BUSY", primary: "QUEUE 7", secondary: "LOAD 63%", detail: ["TABLES: ACTIVE", "YIELD NOTES: OPEN", "FATIGUE: LOW"] },
  pack: { status: "OK", primary: "BATCH 2", secondary: "LABELS OK", detail: ["CONVEYOR: READY", "CRATES: 9", "MISMATCH: 0"] },
  extract: { status: "OK", primary: "TEMP 76F", secondary: "PSI 38", detail: ["LOCK: CLOSED", "VATS: ONLINE", "PIPE STATUS: NORMAL"] },
  security: { status: "OK", primary: "CAMS 15+1", secondary: "FLAGS 0", detail: ["ROOM HEAT: NORMAL", "PATROL: ACTIVE", "SPARE CAM: OFF"] },
  ops: { status: "BUSY", primary: "DOCKER 8", secondary: "HEALTHY", detail: ["CULTIVATION: WATCH", "PROCESSING: BUSY", "REPORT: SEND TO BOSS"] },
  break: { status: "OK", primary: "BREAK 1", secondary: "QUEUE 0", detail: ["COVERAGE: OK", "RECOVERY: NORMAL", "RETURN TIMER: ON"] },
  bath: { status: "OK", primary: "OCC 0/1", secondary: "QUEUE 0", detail: ["LIMIT: ONE", "OVERSTAY: NO", "RETURN: READY"] },
  screen: { status: "OK", primary: "HIRES 0", secondary: "SAVE READY", detail: ["ENTRY: SCREENING", "COLORS: EDITABLE", "ROLES: ASSIGNABLE"] },
  dock: { status: "OK", primary: "WO 4", secondary: "STAGED 2", detail: ["PACKETS: READY", "DELIVERY: ON TIME", "MISSING WO: 0"] },
  warehouse: { status: "OK", primary: "LOG OK", secondary: "SUPPLY 72%", detail: ["ARCHIVE: READY", "DUPLICATES: 0", "SYNC: PENDING BACKEND"] },
  sales: { status: "OK", primary: "MAUI PI2", secondary: "RAM 11/32G", detail: ["CPU: 22%", "STORAGE: 612MB/S", "NET: 42MB/S", "TEMP: 64C"] },
  rd1: { status: "WATCH", primary: "OLLAMA UP", secondary: "MODELS 6", detail: ["LATENCY: 820MS", "QUEUE: 1", "RAM: 18GB", "TPS: 31"] },
  rd2: { status: "OK", primary: "TERM 0", secondary: "SSH 3", detail: ["APPROVALS: REQUIRED", "TARGETS: 3", "LAST EXIT: 0"] },
};

export const gen2WorkerProfiles: Record<string, Gen2WorkerProfile> = {
  boss: {
    npcId: "boss",
    stationRoomId: "boss",
    department: "Executive",
    title: "Boss",
    personality: "Measured, stern, rewards strong work and corrects poor discipline.",
    currentAction: "Reviewing manager summaries",
    steadyMood: "CALM",
    busyMood: "DIRECTIVE",
    reportTarget: "Owner",
    breakPolicy: "Rarely leaves the office; focuses on debriefs and messages.",
  },
  cloneWorker: {
    npcId: "cloneWorker",
    stationRoomId: "clone",
    department: "Cultivation",
    title: "Clone Technician",
    personality: "Careful and routine-driven.",
    currentAction: "Checking clone trays",
    steadyMood: "FOCUSED",
    busyMood: "RUSHED",
    reportTarget: "Cultivation Manager",
    breakPolicy: "Break allowed when clone trays are stable.",
  },
  motherWorker: {
    npcId: "motherWorker",
    stationRoomId: "mother",
    department: "Cultivation",
    title: "Mother Plant Technician",
    personality: "Patient, plant-first, notices small changes.",
    currentAction: "Inspecting mother plants",
    steadyMood: "STEADY",
    busyMood: "CONCERNED",
    reportTarget: "Cultivation Manager",
    breakPolicy: "Break allowed after CO2 and irrigation checks.",
  },
  growWorker: {
    npcId: "growWorker",
    stationRoomId: "grow1",
    department: "Cultivation",
    title: "Grow Room Technician",
    personality: "Energetic and hands-on.",
    currentAction: "Walking plant rows",
    steadyMood: "OK",
    busyMood: "SWEATING",
    reportTarget: "Cultivation Manager",
    breakPolicy: "Manager watches for overheating or skipped breaks.",
  },
  grow2Worker: {
    npcId: "grow2Worker",
    stationRoomId: "grow2",
    department: "Cultivation",
    title: "Grow Room 2 Technician",
    personality: "Hard-working, steady under repeated CPU heat reports.",
    currentAction: "Watching Grow Room 2 device load",
    steadyMood: "READY",
    busyMood: "PUSHING",
    reportTarget: "Cultivation Manager",
    breakPolicy: "Break may be delayed when Grow Room 2 stays hot.",
  },
  grow3Worker: {
    npcId: "grow3Worker",
    stationRoomId: "grow3",
    department: "Cultivation",
    title: "Grow Room 3 Technician",
    personality: "Alert, detail-heavy, tends to over-report heat issues.",
    currentAction: "Watching high-load plant stress",
    steadyMood: "WATCH",
    busyMood: "HOT",
    reportTarget: "Cultivation Manager",
    breakPolicy: "Break is delayed while Grow Room 3 is yellowing.",
  },
  grow4Worker: {
    npcId: "grow4Worker",
    stationRoomId: "grow4",
    department: "Cultivation",
    title: "Grow Room 4 Technician",
    personality: "Calm and methodical.",
    currentAction: "Comparing VM growth stats",
    steadyMood: "OK",
    busyMood: "TUNING",
    reportTarget: "Cultivation Manager",
    breakPolicy: "Break allowed when VM growth and airflow are steady.",
  },
  pottingWorker: {
    npcId: "pottingWorker",
    stationRoomId: "potting",
    department: "Cultivation",
    title: "Potting Specialist",
    personality: "Practical, keeps queues moving.",
    currentAction: "Mixing soil and filling open pots",
    steadyMood: "READY",
    busyMood: "STACKED",
    reportTarget: "Cultivation Manager",
    breakPolicy: "Break allowed only when potting queue is under control.",
  },
  soilWorker: {
    npcId: "soilWorker",
    stationRoomId: "soil",
    department: "Cultivation",
    title: "Dry Room Technician",
    personality: "Patient, careful with humidity and cure timing.",
    currentAction: "Hanging cut plants to dry",
    steadyMood: "CURING",
    busyMood: "RACKED",
    reportTarget: "Cultivation Manager",
    breakPolicy: "Break after a dry batch is handed to trim.",
  },
  cultManager: {
    npcId: "cultManager",
    stationRoomId: "cultMgr",
    department: "Cultivation",
    title: "Cultivation Manager",
    personality: "Balances room health, worker coverage, and telemetry alerts.",
    currentAction: "Reviewing device room reports",
    steadyMood: "REVIEW",
    busyMood: "ASSIST",
    reportTarget: "Boss",
    breakPolicy: "Stays available while any grow room is on watch.",
  },
  processor: {
    npcId: "processor",
    stationRoomId: "trim",
    department: "Processing",
    title: "Processing Worker",
    personality: "Fast but gets tired under heavy queue load.",
    currentAction: "Trimming dried harvest batches",
    steadyMood: "WORKING",
    busyMood: "BACKED UP",
    reportTarget: "Operations Manager",
    breakPolicy: "Break allowed when trim queue is clear.",
  },
  packer: {
    npcId: "packer",
    stationRoomId: "pack",
    department: "Processing",
    title: "Packaging Worker",
    personality: "Consistent and report-friendly.",
    currentAction: "Packing labeled harvest batches",
    steadyMood: "READY",
    busyMood: "BUSY",
    reportTarget: "Operations Manager",
    breakPolicy: "Break allowed after batch handoff.",
  },
  extractor: {
    npcId: "extractor",
    stationRoomId: "extract",
    department: "Processing",
    title: "Extraction Technician",
    personality: "Careful around heat, pressure, and converted batches.",
    currentAction: "Collecting packaged material for extraction",
    steadyMood: "SAFE",
    busyMood: "CAUTION",
    reportTarget: "Operations Manager",
    breakPolicy: "Break delayed while an extract batch is running.",
  },
  opsManager: {
    npcId: "opsManager",
    stationRoomId: "ops",
    department: "Operations",
    title: "Processing Manager",
    personality: "Systematic, tracks processing flow and Docker health.",
    currentAction: "Reviewing processing and container states",
    steadyMood: "ONLINE",
    busyMood: "TRIAGE",
    reportTarget: "Boss",
    breakPolicy: "Covers operations alerts before leaving the desk.",
  },
  processor2: {
    npcId: "processor2",
    stationRoomId: "trim",
    department: "Processing",
    title: "Process Watcher",
    personality: "Good at spotting runaway processes.",
    currentAction: "Checking active process list",
    steadyMood: "SCAN",
    busyMood: "LOAD",
    reportTarget: "Operations Manager",
    breakPolicy: "Break allowed when process queue is stable.",
  },
  processor3: {
    npcId: "processor3",
    stationRoomId: "pack",
    department: "Processing",
    title: "Update Packager",
    personality: "Orderly and version-focused.",
    currentAction: "Sorting available updates",
    steadyMood: "PACK",
    busyMood: "PATCH",
    reportTarget: "Operations Manager",
    breakPolicy: "Break after update list is packaged.",
  },
  processor4: {
    npcId: "processor4",
    stationRoomId: "trim",
    department: "Processing",
    title: "Runtime Assistant",
    personality: "Fast, curious, occasionally impatient.",
    currentAction: "Watching app/runtime processes",
    steadyMood: "READY",
    busyMood: "RUSH",
    reportTarget: "Operations Manager",
    breakPolicy: "Manager delays break during high runtime load.",
  },
  security: {
    npcId: "security",
    stationRoomId: "security",
    department: "Security",
    title: "Security Operator",
    personality: "Quiet, suspicious, escalates fast.",
    currentAction: "Watching camera wall",
    steadyMood: "WATCHING",
    busyMood: "ALERT",
    reportTarget: "Boss",
    breakPolicy: "Break only when patrol has coverage.",
  },
  patrol: {
    npcId: "patrol",
    stationRoomId: "security",
    department: "Security",
    title: "Security Patrol",
    personality: "Direct and territorial.",
    currentAction: "Patrolling heat and overload zones",
    steadyMood: "PATROL",
    busyMood: "ESCALATING",
    reportTarget: "Boss",
    breakPolicy: "Covers security operator breaks.",
  },
  logistics: {
    npcId: "logistics",
    stationRoomId: "warehouse",
    department: "Logistics",
    title: "Report Courier",
    personality: "Organized, timestamp-obsessed, keeps WO numbers clean.",
    currentAction: "Delivering WO packets",
    steadyMood: "ROUTING",
    busyMood: "STACKED",
    reportTarget: "Markdown WO archive",
    breakPolicy: "Break allowed only after report delivery.",
  },
  researcher: {
    npcId: "researcher",
    stationRoomId: "rd1",
    department: "Research",
    title: "AI Systems Researcher",
    personality: "Curious, occasionally distracted by model tests.",
    currentAction: "Running small model experiments",
    steadyMood: "CURIOUS",
    busyMood: "TUNING",
    reportTarget: "Boss",
    breakPolicy: "Break allowed when model queue is idle.",
  },
  secretary: {
    npcId: "secretary",
    stationRoomId: "ops",
    department: "Operations",
    title: "Operations Secretary",
    personality: "Social, notices morale and missing reports.",
    currentAction: "Collecting department lists",
    steadyMood: "ORGANIZED",
    busyMood: "CHASING",
    reportTarget: "Boss",
    breakPolicy: "Can walk departments while managers stay on task.",
  },
  bossSecretary: {
    npcId: "bossSecretary",
    stationRoomId: "boss",
    department: "Executive",
    title: "Boss Secretary",
    personality: "Sharp, discreet, collects reports before they get stale.",
    currentAction: "Collecting reports for the boss",
    steadyMood: "FILING",
    busyMood: "RUNNING",
    reportTarget: "Boss",
    breakPolicy: "Break only after manager report pickup is complete.",
  },
  screenHr: {
    npcId: "screenHr",
    stationRoomId: "screen",
    department: "Grow Ops",
    title: "HR Screening Rep",
    personality: "Patient, organized, keeps new staff profiles tidy.",
    currentAction: "Filing papers and updating staff records",
    steadyMood: "FILING",
    busyMood: "KEYING",
    reportTarget: "Boss",
    breakPolicy: "Keeps the entry desk covered during new-hire screening.",
  },
  maintenance: {
    npcId: "maintenance",
    stationRoomId: "break",
    department: "Maintenance",
    title: "Facility Maintenance",
    personality: "Methodical, keeps shared areas clean and uncluttered.",
    currentAction: "Cleaning bathrooms, break room, and halls",
    steadyMood: "CLEAN",
    busyMood: "SWEEP",
    reportTarget: "Operations Manager",
    breakPolicy: "Rotates cleaning stops before taking a drink break.",
  },
  rdSafety: {
    npcId: "rdSafety",
    stationRoomId: "rd1",
    department: "Research",
    title: "Lab Safety Technician",
    personality: "Unflappable, keeps an extinguisher close during experiments.",
    currentAction: "Watching smoke and flame tests",
    steadyMood: "READY",
    busyMood: "SUPPRESS",
    reportTarget: "Operations Manager",
    breakPolicy: "Stays near R&D while an experiment is active.",
  },
  salesRep: {
    npcId: "salesRep",
    stationRoomId: "sales",
    department: "Sales",
    title: "Sales Strategist",
    personality: "Talkative, converts department findings into client ideas.",
    currentAction: "Interviewing managers for new ideas",
    steadyMood: "PITCH",
    busyMood: "BRAINSTORM",
    reportTarget: "Boss",
    breakPolicy: "Returns to the sales desk after each idea round.",
  },
  salesAssistant: {
    npcId: "salesAssistant",
    stationRoomId: "sales",
    department: "Sales",
    title: "Sales Coordinator",
    personality: "Organized and quick with notes.",
    currentAction: "Preparing sales concepts at the workstation",
    steadyMood: "WRITING",
    busyMood: "PITCH",
    reportTarget: "Sales Strategist",
    breakPolicy: "Covers the sales desk while Cass is meeting managers.",
  },
};

export const gen2WorkerIdentity: Record<string, Gen2WorkerIdentity> = {
  boss: { name: "Oakley", sex: "M", age: 61, workEthic: "HIGH", evaluation: "Turns manager notes into owner-facing debriefs." },
  bossSecretary: { name: "Mara", sex: "F", age: 34, workEthic: "EXCELLENT", evaluation: "Collects manager reports before they become stale." },
  cloneWorker: { name: "Iris", sex: "F", age: 28, workEthic: "STEADY", evaluation: "Careful clone-room checks with low error rate." },
  motherWorker: { name: "Mina", sex: "F", age: 31, workEthic: "HIGH", evaluation: "Strong plant awareness and reliable PC thermal notes." },
  growWorker: { name: "Tessa", sex: "F", age: 30, workEthic: "HIGH", evaluation: "Keeps Grow Room 1 steady and reports water/growth changes clearly." },
  grow2Worker: { name: "Gigi", sex: "F", age: 26, workEthic: "EXCELLENT", evaluation: "Grow Room 2 has been high CPU for several reports; she may need help or a raise." },
  grow3Worker: { name: "Nico", sex: "M", age: 29, workEthic: "HIGH", evaluation: "Catches heat stress early in Grow Room 3." },
  grow4Worker: { name: "Lena", sex: "F", age: 33, workEthic: "STEADY", evaluation: "Keeps VM/device stats calm and organized." },
  pottingWorker: { name: "Owen", sex: "M", age: 37, workEthic: "STEADY", evaluation: "Keeps potting queues from piling up." },
  soilWorker: { name: "Sage", sex: "F", age: 32, workEthic: "HIGH", evaluation: "Tracks drying time and delivers clean harvest batches to trim." },
  cultManager: { name: "Dan", sex: "M", age: 44, workEthic: "EXCELLENT", evaluation: "Balances cultivation staffing against device-room load." },
  processor: { name: "Rafa", sex: "M", age: 30, workEthic: "HIGH", evaluation: "Good with active process queues." },
  processor2: { name: "June", sex: "F", age: 27, workEthic: "STEADY", evaluation: "Strong runtime watcher." },
  processor3: { name: "Theo", sex: "M", age: 35, workEthic: "HIGH", evaluation: "Reliable update/package sorter." },
  processor4: { name: "Ari", sex: "F", age: 24, workEthic: "STEADY", evaluation: "Fast but needs pacing during high load." },
  packer: { name: "Pax", sex: "M", age: 32, workEthic: "HIGH", evaluation: "Keeps available updates batched cleanly." },
  extractor: { name: "Sloane", sex: "F", age: 39, workEthic: "EXCELLENT", evaluation: "Turns packaged product into extract batches and delivers finished output." },
  opsManager: { name: "Riley", sex: "F", age: 43, workEthic: "HIGH", evaluation: "Keeps processing staff and Docker operations covered." },
  security: { name: "Knox", sex: "M", age: 42, workEthic: "HIGH", evaluation: "Escalates heat and overload issues quickly." },
  patrol: { name: "Vega", sex: "F", age: 36, workEthic: "HIGH", evaluation: "Good patrol discipline and room coverage." },
  logistics: { name: "Miles", sex: "M", age: 41, workEthic: "EXCELLENT", evaluation: "Keeps WO report packets timestamped and sorted." },
  researcher: { name: "Elia", sex: "F", age: 38, workEthic: "HIGH", evaluation: "Tracks Ollama model behavior and test terminals." },
  secretary: { name: "Noor", sex: "F", age: 29, workEthic: "STEADY", evaluation: "Keeps Ops notes and department lists moving." },
  screenHr: { name: "Harper", sex: "F", age: 40, workEthic: "HIGH", evaluation: "Keeps new hires screened before they hit the floor." },
  maintenance: { name: "Mack", sex: "M", age: 46, workEthic: "STEADY", evaluation: "Keeps bathrooms, break room, and traffic lanes clean." },
  rdSafety: { name: "Sol", sex: "M", age: 34, workEthic: "HIGH", evaluation: "Responds quickly to smoke and flame during model tests." },
  salesRep: { name: "Cass", sex: "F", age: 36, workEthic: "HIGH", evaluation: "Turns manager interviews into useful sales concepts." },
  salesAssistant: { name: "Reese", sex: "F", age: 27, workEthic: "STEADY", evaluation: "Keeps sales workstation coverage and organizes incoming ideas." },
};

export const gen2PerformanceBriefs = [
  "Dan: Grow Room 2 has been high CPU for several reports. Gigi is working extra hard and may need another worker assigned.",
  "Boss: Dan reports Gigi is carrying repeated high-load checks. Consider help, raise, or workload balancing.",
  "Security: Grow Room 3 is yellowing after long heavy load. Escalated to boss and cultivation manager.",
  "Logistics: Hourly report packets are queued for security, cultivation, operations, R&D, sales, logistics, and boss.",
  "Sage: Harvest batches are drying on schedule and will be handed to trim as soon as humidity settles.",
];

export const gen2BossHotKeys: Gen2HotKey[] = [
  { key: "1", label: "Good Work", message: "Good work. Keep that pace.", expectedResponse: "Mood improves, workers stay at station longer." },
  { key: "2", label: "Focus Up", message: "Focus up and finish the current list.", expectedResponse: "Break chance drops, workload stress rises slightly." },
  { key: "3", label: "Take Five", message: "Take a short break when your station is stable.", expectedResponse: "Eligible workers rotate to break room." },
  { key: "4", label: "Report In", message: "Compile your list and send it to your manager.", expectedResponse: "Workers generate manager-facing report packets." },
  { key: "5", label: "Manager Assist", message: "Managers, assist overloaded staff.", expectedResponse: "Managers move toward departments under pressure." },
  { key: "6", label: "Security Sweep", message: "Security, sweep for overloads and heat warnings.", expectedResponse: "Security prioritizes alerts and boss escalation." },
  { key: "7", label: "Docker Check", message: "Operations, verify Docker health and container uptime.", expectedResponse: "Ops report focuses Docker containers." },
  { key: "8", label: "Ollama Check", message: "Research, verify Ollama and loaded models.", expectedResponse: "Research report focuses model status and latency." },
  { key: "9", label: "Host Check", message: "Check the GMKtec M7 host health.", expectedResponse: "Host report focuses CPU, RAM, fans, thermals, disk, network." },
  { key: "0", label: "Debrief", message: "Boss, compile the latest debrief.", expectedResponse: "Boss prepares owner-facing summary with WO references." },
];

export const gen2ReportLogPath = "docs/gen2-wo-report-log.md";
